(* This file was auto-generated based on "sintatico.msg". *)
(* Please note that the function [message] can raise [Not_found]. *)

let message = fun s ->
				match s with
				| 0 ->		"0: Esperava 'program'\n"
				| 1 -> "1:Esperava nome do programa\n"
				| 2 -> "2:Esperava ';'\n"
				| 3 -> "3:Esperava declaracao de variavel ou declaracao de funcao ou um 'begin'\n"
				| 21  -> 	"21: Esperava identificadores para as variaveis\n"
				| 23  ->	"23: Esperava um tipo\n"
				| 25  ->	"25: Esperava ';'\n"
				| 7 ->		"7: Esperava ',' ou ':'\n"
				| 8 ->		"8: Esperava identificador\n"
				| 28 -> 	"28: Esperava um tipo\n"
				| 29 ->		"29: Esperava ';'\n"
				| 155 ->	"<155: Esperava declaracao de variaveis ou 'begin'\n"
				| 4 ->		"4: Esperava identificador\n"
				| 5 ->		"5: Esperava '('\n"
				| 6 ->		"6: Esperava lista de parametros\n"
				| 158 ->	"158: Esperava um tipo\n"
				| 11 ->		"11: Esperava ')'\n"
				| 12 ->		"12: Esperava ':'\n"
				| 13 ->		"13: Esperava um tipo\n"
				| 19 ->		"19: Esperava ';'\n"
				| 20 ->		"20: Esperava por declaracao de variaveis ou 'begin'\n"
				| 32 ->		"32: Esperava comandos ou 'end'\n"
				| 152 ->	"152: Esperava 'end'\n"
				| 153 ->	"153: Esperava ';'\n"
				| 166 -> 	"166: Esperava declaracao de funcao ou declaracao de variaveis ou 'begin'\n"
				| 33 -> 	"33: Esperava expressao ou '(' seguido de expressao\n"
				| 78 -> 	"78: Esperava operador ou 'DO'\n"
				| 44 -> 	"44: Esperava expressao ou '('\n"
				| 45 -> 	"45: Esperava operador, 'TO', 'DO', ':', 'Then', ')'\n"
				| 46 -> 	"46: Esperava expressao\n"
				| 49 -> 	"49: Esperava expressao\n"
				| 51 -> 	"51: Esperava expressao\n"
				| 52 -> 	"52: Esperava operador, 'TO', 'DO', ':', 'Then', ')', ';'\n"
				| 55 -> 	"55: Esperava expressao\n"
				| 56 -> 	"56: Esperava operador, 'TO', 'DO', ':', 'Then', ')', ';'\n"
				| 59 -> 	"59: Esperava expressao ou '('\n"
				| 60 -> 	"60: Esperava operador, 'TO', 'DO', ':', 'Then', ')', ';'\n"
				| 57 -> 	"57: Esperava expressao ou '('\n"
				| 58 -> 	"58: Esperava operador, 'TO', 'DO', ':', 'Then', ')', ';'\n"
				| 61 -> 	"61: Esperava expressao ou '('\n"
				| 62 -> 	"62: Esperava operador, 'TO', 'DO', ':', 'Then', ')', ';'\n"
				| 63 -> 	"63: Esperava expressao ou '('\n"
				| 64 -> 	"64: Esperava operador, 'TO', 'DO', ':', 'Then', ')', ';'\n"
				| 65 -> 	"65: Esperava expressao ou '('\n"
				| 66 -> 	"66: Esperava operador, 'TO', 'DO', ':', 'Then', ')', ';'\n"
				| 67 -> 	"67: Esperava expressao ou '('\n"
				| 68 -> 	"68: Esperava operador, 'TO', 'DO', ':', 'Then', ')', ';'\n"
				| 79 -> 	"79: Esperava 'begin'\n"
				| 80 -> 	"80: Esperava comandos ou 'end'\n"
				| 149 ->	"149: Esperava 'end'\n"
				| 150 ->	"150: Esperava ';'\n"
				| 53 -> 	"53: Esperava expressao ou '('\n"
				| 69 -> 	"69: Esperava expressao ou '('\n"
				| 70 -> 	"70: Esperava operador, 'TO', 'DO', ':', 'Then', ')', ';'\n"
				| 40 -> 	"40: Esperava operador, 'TO', 'DO', ':', 'Then', ')', ';'\n"
				| 39 -> 	"39: Esperava expressao ou '('\n"
				| 43 -> 	"43: Esperava expressao\n"
				| 162 ->	"162: Esperava comandos ou 'end.'\n"
				| 81 -> 	"81: Esperava '('\n"
				| 82 -> 	"82: Esperava expressao ou '('\n"
				| 75 -> 	"75: Esperava Operador, ')' ou ','\n"
				| 76 ->		"76: Esperava expressao ou '('\n"
				| 84 -> 	"84: Esperava ';'\n"
				| 86 -> 	"86: Esperava '('\n"
				| 87 -> 	"87: Esperava expressao ou '('\n"
				| 89 -> 	"89: Esperava ';'\n"
				| 91 -> 	"91: Esperava expressao ou '('\n"
				| 92 -> 	"92: Esperava operador ou ';'\n"
				| 139 ->	"139: Esperava comandos ou 'end'\n"
				| 163 ->	"163: Esperava 'end.'\n"
				| 94 -> 	"94: Esperava expressao ou '('\n"
				| 95 -> 	"95: Esperava operador ou ';'\n"
				| 97 -> 	"97: Esperava expressao ou '('\n"
				| 98 -> 	"98: Esperava operador ou 'then'\n"
				| 99 -> 	"99: Esperava 'begin'\n"
				| 100 ->	"100:Esperava comandos ou 'end'\n"
				| 141 ->	"141: Esperava 'end'\n"
				| 142 ->	"142: Esperava 'else' ou 'end' \n"
				| 143 ->	"143: Esperava 'begin'\n"
				| 144 ->	"144: Esperava comandos ou 'end'\n"
				| 145 ->	"145: Esperava 'end'\n"
				| 146 ->	"146: Esperava ';'\n"
				| 37 -> 	"37: Esperava '(' seguido ou nao de parametros \n"
				| 115 ->	"115: Esperava ':='\n"
				| 41 -> 	"41: Esperava um identificador\n"
				| 116 ->	"116: Esperava expressao ou '('\n"
				| 117 ->	"117: Esperava ';' ou operador\n"
				| 38 -> 	"38: Esperava expressao ou ')'\n"
				| 101 ->	"101: Esperava identificador\n"
				| 103 ->	"103: Esperava ':='\n"
				| 104 ->	"104: Esperava expressao \n"
				| 105 ->	"105: Esperava operador ou 'TO'\n"
				| 106 ->	"106: Esperava expressao\n"
				| 107 ->	"107: Esperava operador ou 'DO'\n"
				| 108 ->	"108: Esperava 'begin'\n"
				| 109 ->	"109: Esperava lista de comandos ou 'end'\n"
				| 136 ->	"136: Esperava 'end'\n"
				| 137 ->	"137: Esperava ';'\n"
				| 164 ->	"164: Esperava EOF Fim de arquivo\n"
				| 110 ->	"110: Esperava um identificador\n"
				| 111 ->	"111: Esperava 'OF'\n"
				| 112 ->	"112: Esperava cases\n"
				| 131 ->	"131: Esperava ':'\n"
				| 132 ->	"132: Esperava um comando\n"
				| 134 ->	"134: Esperava ':'\n"
				| 129 ->	"129: Esperava ';'\n"
				| 114 ->	"114: Esperava ':='\n"
				| 128 ->	"128: Esperava 'end'\n"
				| _   ->	raise Not_found